#!/bin/bash

case "$1" in
  "client")
    exec ghcid -c "cabal v2-repl lambdachat-client" \
      --restart cabal.project \
      --restart lambdachat/src/ \
      --restart lambdachat-prelude/ \
      --restart lambdachat-client/lambdachat-client.cabal
    ;;

  "lib")
    exec ghcid -c "cabal v2-repl lambdachat" \
      --restart cabal.project \
      --restart lambdachat/lambdachat.cabal
    ;;

  "server")
    exec ghcid -c "cabal v2-repl lambdachat-server" \
      --restart cabal.project \
      --restart lambdachat/src/ \
      --restart lambdachat-prelude/src/ \
      --restart lambdachat-server/lambdachat-server.cabal
    ;;

  *)
    echo "Usage: ./repl (client | lib | server)"
    ;;
esac
